spring:
  application:
    name: resilience4j-practice
  jackson:
    serialization:
      indent-output: true
server:
  port: 9080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        resilience4j.circuitbreaker.calls: true

info:
  name: ${spring.application.name}
  description: resilience4j practice
  environment: ${spring.profiles.active}
  version: 0.0.1


resilience4j:
  circuitbreaker:
    configs:
      default: # 기본 config 명
        registerHealthIndicator: true  # Resilience4j의 Health Indicator 등록 여부
        slidingWindowType: time_based  # 슬라이딩 윈도우 유형 (시간 기반)
        slidingWindowSize: 10  # 슬라이딩 윈도우 크기
        minimumNumberOfCalls: 10  # 최소 호출 횟수, 실패 비율을 계산하기 위한 최소 호출 횟수
        slowCallRateThreshold: 100  # 느린 호출 비율 임계값
        slowCallDurationThreshold: 60000  # 느린 호출로 간주되는 기준 응답 시간(ms)
        failureRateThreshold: 50  # 실패 비율 임계값
        permittedNumberOfCallsInHalfOpenState: 10  # Half-open 상태에서 허용되는 호출 횟수
        waitDurationInOpenState: 10  # 서킷이 Open 상태에서 Half-open 상태로 변경되기 전 대기하는 시간 [s]

    instances:
      circuit-test-5000: # circuitbreaker name
        baseConfig: default  # 기본 config 지정 (Ex-circuitbreaker.configs.{default})
        slowCallDurationThreshold: 900  # 응답시간이 느린 것으로 판단할 기준 시간 [ms]

      circuit-db-select-200:
        baseConfig: default
        slowCallDurationThreshold: 200  # 응답시간이 느린 것으로 판단할 기준 시간 [ms]

      circuit-db-select-300:
        baseConfig: default
        slowCallDurationThreshold: 300  # 응답시간이 느린 것으로 판단할 기준 시간 [ms]

        